apiVersion: v1
kind: Pod
metadata:
  name: "app-pod"
  labels:
    app: "app-pod"
spec:
  containers:
  - name: app
    image: ar989827/lanchonete:v1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: prod
      - name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-srv/lanchonetedb
      - name: SPRING_DATASOURCE_USERNAME
        value: sa
      - name: SPRING_DATASOURCE_PASSWORD
        value: password
      - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
        value: com.mysql.cj.jdbc.Driver
      - name: SPRING_JPA_HIBERNATE_DDL-AUTO
        value: none
      - name: SPRING_JPA_DATABASE-PLATFORM
        value: org.hibernate.dialect.MySQL8Dialect
    ports:
    - containerPort:  8080