apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "rootpassword"
      - name: MYSQL_DATABASE
        value: "lanchonetedb"
      - name: MYSQL_USER
        value: "sa"
      - name: MYSQL_PASSWORD
        value: "password"
    ports:
    - containerPort:  3306
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: lanchonete-pvc